### ISSUE TITLE
spark-shell executor pods won't start up with latest (post 2023.06.08)

### ISSUE THREAD

**Issue by mentics** [canonical/spark-client-snap#68]
## Steps to reproduce
1. Try to run spark-client.spark-shell

## Expected behavior
Executor pods start up.

## Actual behavior

They fail repeatedly, with error in the logs:
`error: unknown command "executor", see 'pebble help'`

## Versions

Operating system: Ubuntu 22.04.2 LTS

## Log output

```error: unknown command "executor", see 'pebble help'```

## Additional context

It was working last week and then I added a new node to my cluster that pulled the new image. Then the nodes using the old image worked, but those using the new image did not. It seems likely the problem is in the image: ghcr.io/canonical/charmed-spark:3.4.0-22.04_edge

**Comment by deusebio** [comment]
Hi @mentics ! Thanks for reporting this. Yes, we have recently (today) upgraded the [spark image](https://github.com/canonical/charmed-spark-rock/pull/23) to use pebble as entrypoint, which is now the new standard entrypoint required by ROCK-compliant OCI images. 

This change unfortunately is not backward compatible (as changes the entrypoint) and broke things on the spark client snap side (we are still on edge risks here). I'm going to fix this shortly. I'll refer this issue in the PR so you can track when this is resolved

**Comment by deusebio** [comment]
As a temporarily workaround you can also:

1. Create a podTemplate.yaml like [this](https://github.com/canonical/charmed-spark-rock/pull/23/files#diff-de9a13b19681e3a36d605f5fd2939855883d693d61ad2e5433bd6f240c9bc93c) one. 
2. Refer to that file in the configuration, similarly to what has been done [here](https://github.com/canonical/charmed-spark-rock/pull/23/files#diff-42c4bbc2d848486731ee3dacc12ba05a9be8df2936f2cfaea32f643e73994bc6). You can either modify the `/var/snap/spark-client/41/etc/spark8t/spark-defaults.conf` file or you can provide those settings via the --conf arguments in the cli

**Comment by mentics** [comment]
> As a temporarily workaround you can also:
> 
> 1. Create a podTemplate.yaml like [this](https://github.com/canonical/charmed-spark-rock/pull/23/files#diff-de9a13b19681e3a36d605f5fd2939855883d693d61ad2e5433bd6f240c9bc93c) one.
> 2. Refer to that file in the configuration, similarly to what has been done [here](https://github.com/canonical/charmed-spark-rock/pull/23/files#diff-42c4bbc2d848486731ee3dacc12ba05a9be8df2936f2cfaea32f643e73994bc6). You can either modify the `/var/snap/spark-client/41/etc/spark8t/spark-defaults.conf` file or you can provide those settings via the --conf arguments in the cli

Thank you! That worked.

**Comment by deusebio** [comment]
The issue should have been resolved, as we have rolled back the UX for the Spark OCI image. It is not needed to patch the pod templates and  configuration files anymore
