### ISSUE TITLE
Charmed Spark Image: 3.4-22.04 default's to root

### ISSUE THREAD

**Issue by 106106** [canonical/spark-client-snap#80]
Hi Spark contributors,

It seems like the default user in the charmed-spark:3.4-22.04 image is root and
when launching spark applications the processes inside the driver and executor pods
(pebble, java/spark) are launched as root as well.

Is this intended or can the default user and processes be "de-privileged" to a Spark user for example?

Thanks for your time!

**Comment by deusebio** [comment]
This had been addressed [here](https://github.com/canonical/charmed-spark-rock/pull/35). Once the beta channel will be promoted to the revision including this, this should be fixed. 

Meanwhile one could test and try out things by specifying the edge image in when running Spark jobs using:

```
--conf spark.kubernetes.container.image=ghcr.io/canonical/charmed-spark:3.4.1-22.04_edge
```
